### ISSUE TITLE
Improve login and register buttons

### ISSUE THREAD

**Issue by cyber-venom003** [GeekHaven/find-my-senior#14]
### Add some color and border to buttons on login and register screen
Color should be in accordance with splash screen.
Do attach the screenshots while making PR.

**Comment by Codedude1** [comment]
I would like to work on this.

**Comment by mysterio0801** [comment]
I want to work on it.

**Comment by cyber-venom003** [comment]
Let others get some chance @mysterio0801 .You already have two issues assigned in this repo, first solve them, after that I would assign it to you.

**Comment by greenblade29** [comment]
can I work on this @cyber-venom003 ?

**Comment by cyber-venom003** [comment]
Go ahead @greenblade29

**Comment by cyber-venom003** [comment]
Go ahead @mysterio0801

**Comment by mysterio0801** [comment]
> Go ahead @mysterio0801

Thanks @cyber-venom003 🙌

**Comment by mysterio0801** [comment]
I have sent the pr @cyber-venom003 . The screenshot of the same is attached below.

![WhatsApp Image 2020-10-15 at 2 40 57 AM](https://user-images.githubusercontent.com/54456976/96045977-5b9c9500-0e90-11eb-8d7d-323a96c225a2.jpeg)

**Comment by cyber-venom003** [comment]
Fixed in #20 by @mysterio0801
