### ISSUE TITLE
Implement ListView in dashboard

### ISSUE THREAD

**Issue by cyber-venom003** [GeekHaven/find-my-senior#17]
#### List tile would contain following:
- Name of Senior
- Branch and Batch of senior
- Clicking on tile would redirect to profile page of that senior.( HINT: Pass the details of senior from dashboard to profile page using navigator)

**Comment by mysterio0801** [comment]
I want to work on this.

**Comment by cyber-venom003** [comment]
go ahead @mysterio0801

**Comment by Cybertron-Avneesh** [comment]
@mysterio0801 any updates?

**Comment by mysterio0801** [comment]
I am working on it. After the last pr is merged there are few issues coming. Working to sort out things.

**Comment by mysterio0801** [comment]
@cyber-venom003 I have attached the pr related to this issue.
