### ISSUE TITLE
Create a splash screen

### ISSUE THREAD

**Issue by cyber-venom003** [GeekHaven/find-my-senior#2]
Create a splash screen for the app.
Note: You should implement is using Launcher Theme instead of using Timer-based.
Attach a screenshot in the comment while making PR.

**Comment by JLodha** [comment]
I want to work on this

**Comment by Cybertron-Avneesh** [comment]
@JLodha go ahead 🎉.

**Comment by cyber-venom003** [comment]
@JLodha go ahead

**Comment by cyber-venom003** [comment]
@JLodha take the logo from logo directory of project.
First update your fork, because PR #8 has changed the original repo.

**Comment by greenblade29** [comment]
Can I work on this @Cybertron-Avneesh ?

**Comment by cyber-venom003** [comment]
> 
> 
> Can I work on this @Cybertron-Avneesh ?

Go ahead @greenblade29

**Comment by lazyp4nd4** [comment]
Nice work @greenblade29 !
