### ISSUE TITLE
Design a logo for app

### ISSUE THREAD

**Issue by cyber-venom003** [GeekHaven/find-my-senior#4]
Design a logo for app that would be used in splash screen as mentioned in #2 .
Add logo in SVG or PNG format or both to `/logo/` directory.

Then create a PR.

**Comment by Codedude1** [comment]
Hey! I would like to work on this.

**Comment by cyber-venom003** [comment]
Go ahead @Codedude1

**Comment by Codedude1** [comment]
Hey! Can you please review this?
![FindMySenior](https://user-images.githubusercontent.com/53789050/95663657-bb2c3500-0b5e-11eb-9d30-84c53ffacf3f.png)
