### ISSUE TITLE
Implement searching using filters

### ISSUE THREAD

**Issue by cyber-venom003** [GeekHaven/find-my-senior#7]
### Implement searching of seniors in home page using following filters
- Skill Filters
- Branch Filters
 - Email Search
- Name Search
#### Skill filter would contain following skills: 
- All technical skills like: AppD, WebD, IoT, AI/ML.
- All management skills like fest executive, fest coordinators etc.

**Comment by AnuVe** [comment]
Hey! can i work on this?

**Comment by cyber-venom003** [comment]
Go ahead @AnuVe

**Comment by cyber-venom003** [comment]
Any updates @AnuVe ??

**Comment by AnuVe** [comment]
Hey @cyber-venom003 I'm currently working on fetching search keywords from firestore.
I have incorporated search in app bar.
![Screenshot_20201014-165051](https://user-images.githubusercontent.com/58393983/96087409-6e8b8580-0ee1-11eb-8453-bea588e660ba.png)
![Screenshot_20201014-165033](https://user-images.githubusercontent.com/58393983/96087444-7a774780-0ee1-11eb-960b-79d8ea279931.png)

**Comment by cyber-venom003** [comment]
Ok nice, keep doing. 💯
