### ISSUE TITLE
Add App-icon

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [GeekHaven/find-my-senior#9]
Use the logo from `/logo/` and add app icon mainly for android.

Hint: use https://appicon.co/ to generate icons.

**Comment by geeks5551** [comment]
hey @Cybertron-Avneesh can i work on this issue?

**Comment by Cybertron-Avneesh** [comment]
Sure @geeks5551 .

**Comment by dheeraj-code** [comment]
I want to work on this issue.

**Comment by lazyp4nd4** [comment]
Okay. I will assign it to you. However, we will be closing the issue by selecting the best of either your contribution or @geeks5551 's contribution.

**Comment by cyber-venom003** [comment]
Fixed in #8 by @dheeraj-code !
